# Generated by Django 3.2.8 on 2021-10-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location_town', models.CharField(max_length=50)),
                ('location_county', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('has_visitor_centre', models.BooleanField()),
                ('opening_hours', models.CharField(max_length=50)),
                ('tour_bookable', models.BooleanField(blank=True, null=True)),
                ('tour_length', models.DurationField(blank=True, null=True)),
                ('tour_times', models.TimeField()),
                ('tour_price_adult', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tour_price_child', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('distillery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gins.distillery')),
            ],
        ),
    ]
