# Generated by Django 3.2.8 on 2021-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillery',
            name='tour_times',
            field=models.CharField(choices=[('12:00', '12 noon'), ('14:00', '2pm'), ('16:00', '4pm')], max_length=15),
        ),
    ]
