# Generated by Django 3.2.8 on 2021-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0002_alter_distillery_tour_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillery',
            name='tour_times',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
