# Generated by Django 3.2.8 on 2021-10-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0003_alter_distillery_tour_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='opening_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distillery',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
