# Generated by Django 3.2.8 on 2021-10-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0004_auto_20211031_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distillery',
            options={'verbose_name_plural': 'Distilleries'},
        ),
        migrations.AddField(
            model_name='distillery',
            name='location_province',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
