# Generated by Django 3.2.8 on 2021-11-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0006_alter_distillery_location_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distillery',
            old_name='location_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='opening_days',
            new_name='daysopen',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='opening_hours',
            new_name='hoursopen',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='tour_bookable',
            new_name='tourbookable',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='tour_length',
            new_name='tourlength',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='tour_price_adult',
            new_name='tourpriceadult',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='tour_price_child',
            new_name='tourpricechild',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='tour_times',
            new_name='tourtimes',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='location_town',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='distillery',
            old_name='has_visitor_centre',
            new_name='visitorcentre',
        ),
        migrations.RemoveField(
            model_name='distillery',
            name='location_province',
        ),
        migrations.AddField(
            model_name='distillery',
            name='province',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
